# Generated by Django 3.0.4 on 2020-03-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='current_time_zone',
            field=models.CharField(default='ETC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='known_languages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='known_languages', to='users.Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='primary_language', to='users.Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='wanted_languages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wanted_languages', to='users.Language'),
        ),
    ]
