# Generated by Django 3.0.4 on 2020-03-31 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eTutor', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='known_languages',
        ),
        migrations.AddField(
            model_name='user',
            name='known_languages',
            field=models.ManyToManyField(blank=True, null=True, related_name='known_languages', to='eTutor.Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_language', to='eTutor.Language'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='wanted_languages',
        ),
        migrations.AddField(
            model_name='user',
            name='wanted_languages',
            field=models.ManyToManyField(blank=True, null=True, related_name='wanted_languages', to='eTutor.Language'),
        ),
    ]
