# Generated by Django 3.0.4 on 2020-03-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eTutor', '0001_initial'),
        ('users', '0002_auto_20200331_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_time_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='known_languages',
            field=models.ManyToManyField(related_name='known_languages', to='eTutor.Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wanted_languages',
            field=models.ManyToManyField(related_name='wanted_languages', to='eTutor.Language'),
        ),
    ]
