# Generated by Django 3.0.4 on 2020-04-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eTutor', '0006_timezone'),
        ('users', '0003_auto_20200331_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_time_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_time_zone', to='eTutor.TimeZone'),
        ),
    ]
