# Generated by Django 3.0.4 on 2020-04-01 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eTutor', '0002_friendship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='accepted',
            new_name='friends',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='requester',
        ),
        migrations.AddField(
            model_name='friendship',
            name='accepted_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendship',
            name='accepted_two',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
