# Generated by Django 3.0.4 on 2020-04-06 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eTutor', '0004_likedislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='accepted_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.PositiveIntegerField(default=0)),
                ('dm', models.PositiveIntegerField(default=0)),
                ('friend', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
