# Generated by Django 3.0.4 on 2020-04-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eTutor', '0005_notifications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='dm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='friend',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='video',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
