# Generated by Django 3.0.4 on 2020-04-07 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eTutor', '0008_dm_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm_notifications',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_notifications', to='eTutor.Room'),
        ),
        migrations.AlterField(
            model_name='dm_notifications',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_dm_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
